### ISSUE TITLE
Kubeflow v1.6.1 -- AWS release v1.6.1-aws-b1.0.1 -- Terraform Deployment Not Working

### ISSUE THREAD

**Issue by renanmb** [awslabs/kubeflow-manifests#631] opened 2023-03-21 20:54 UTC
**Describe the bug**
Aparently it seems a race condition error because the managed-node-group is not yet created and the Addon(coredns and some of the csi_drivers) is waiting indefinitely to be deployed, ultimately leading to a TF timeout.

I also imagine might be some IRSA related issues ,but I could be wrong.

Race Condition related errors: aws_coredns, aws_ebs_csi_driver.
Possibly IRSA related errors: aws-load-balancer-controller, cert-manager, secrets-store-csi-driver, aws-fsx-csi-driver, aws-efs-csi-driver.

I am very confused on how to proceed to fix the issues. Maybe the documentation is outdated also.

**Steps To Reproduce**
When follow the instructions from kubeflow-on-aws website run the $ make deploy

**Expected behavior**
It might have raised Warnings, but not an Error

**Environment**
* Terraform Deployment  cognito-rds-s3
KUBEFLOW_RELEASE_VERSION=v1.6.1
AWS_RELEASE_VERSION=v1.6.1-aws-b1.0.1
Client Version: v1.25.0
Kustomize Version: v4.5.7

**Terraform feedback*
module.eks_blueprints_kubernetes_addons.module.aws_load_balancer_controller[0].module.helm_addon.helm_release.addon[0]: Still creating... [20m0s elapsed]
╷
│ Warning: Resource targeting is in effect
│ 
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes
│ requested by the current configuration.
│ 
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or
│ mistakes, or when Terraform specifically suggests to use it as part of an error message.
╵
╷
│ Warning: Applied changes may be incomplete
│ 
│ The plan was created with the -target option in effect, so some changes requested in the configuration may have been ignored and the
│ output values may not be fully updated. Run the following command to verify that no other changes are pending:
│     terraform plan
│ 
│ Note that the -target option is not suitable for routine use, and is provided only for exceptional situations such as recovering from
│ errors or mistakes, or when Terraform specifically suggests to use it as part of an error message.
╵
╷
│ Warning: Redundant empty provider block
│ 
│   on cognito-rds-s3-components/main.tf line 1:
│    1: provider "aws" {
│ 
│ Earlier versions of Terraform used empty provider blocks ("proxy provider configurations") for child modules to declare their need to
│ be passed a provider configuration by their callers. That approach was ambiguous and is now deprecated.
│ 
│ If you control this module, you can migrate to the new declaration syntax by removing all of the empty provider "aws" blocks and then
│ adding or updating an entry like the following to the required_providers block of module.kubeflow_components:
│     aws = {
│       source = "hashicorp/aws"
│       configuration_aliases = [
│         aws.aws,
│         aws.virginia,
│       ]
│     }
│ 
│ (and one more similar warning elsewhere)
╵
╷
│ Warning: Experimental feature "module_variable_optional_attrs" is active
│ 
│   on .terraform/modules/eks_blueprints_kubernetes_addons.ondat/locals.tf line 2, in terraform:
│    2:   experiments = [module_variable_optional_attrs]
│ 
│ Experimental features are subject to breaking changes in future minor or patch releases, based on feedback.
│ 
│ If you have feedback on the design of this feature, please open a GitHub issue to discuss it.
│ 
│ (and 7 more similar warnings elsewhere)
╵
╷
│ Warning: Helm release "aws-load-balancer-controller" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then run Terraform again.
│ 
│   with module.eks_blueprints_kubernetes_addons.module.aws_load_balancer_controller[0].module.helm_addon.helm_release.addon[0],
│   on .terraform/modules/eks_blueprints_kubernetes_addons/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {
│ 
╵
╷
│ Warning: Helm release "cert-manager" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then run Terraform again.
│ 
│   with module.eks_blueprints_kubernetes_addons.module.cert_manager[0].module.helm_addon.helm_release.addon[0],
│   on .terraform/modules/eks_blueprints_kubernetes_addons/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {
│ 
╵
╷
│ Warning: Helm release "secrets-store-csi-driver" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then run Terraform again.
│ 
│   with module.eks_blueprints_kubernetes_addons.module.secrets_store_csi_driver[0].module.helm_addon.helm_release.addon[0],
│   on .terraform/modules/eks_blueprints_kubernetes_addons/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {
│ 
╵
╷
│ Warning: Helm release "aws-fsx-csi-driver" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then run Terraform again.
│ 
│   with module.eks_blueprints_kubernetes_addons.module.aws_fsx_csi_driver[0].module.helm_addon.helm_release.addon[0],
│   on .terraform/modules/eks_blueprints_kubernetes_addons/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {
│ 
╵
╷
│ Warning: Helm release "aws-efs-csi-driver" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then run Terraform again.
│ 
│   with module.eks_blueprints_kubernetes_addons.module.aws_efs_csi_driver[0].module.helm_addon.helm_release.addon[0],
│   on .terraform/modules/eks_blueprints_kubernetes_addons/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {
│ 
╵
╷
│ Error: unexpected EKS Add-On (kubeflow-v1:coredns) state returned during creation: timeout while waiting for state to become 'ACTIVE' (last state: 'DEGRADED', timeout: 20m0s)
│ [WARNING] Running terraform apply again will remove the kubernetes add-on and attempt to create it again effectively purging previous add-on configuration
│ 
│   with module.eks_blueprints_kubernetes_addons.module.aws_coredns[0].aws_eks_addon.coredns[0],
│   on .terraform/modules/eks_blueprints_kubernetes_addons/modules/kubernetes-addons/aws-coredns/main.tf line 12, in resource "aws_eks_addon" "coredns":
│   12: resource "aws_eks_addon" "coredns" {
│ 
╵
╷
│ Error: unexpected EKS Add-On (kubeflow-v1:aws-ebs-csi-driver) state returned during creation: timeout while waiting for state to become 'ACTIVE' (last state: 'DEGRADED', timeout: 20m0s)
│ [WARNING] Running terraform apply again will remove the kubernetes add-on and attempt to create it again effectively purging previous add-on configuration
│ 
│   with module.eks_blueprints_kubernetes_addons.module.aws_ebs_csi_driver[0].aws_eks_addon.aws_ebs_csi_driver[0],
│   on .terraform/modules/eks_blueprints_kubernetes_addons/modules/kubernetes-addons/aws-ebs-csi-driver/main.tf line 7, in resource "aws_eks_addon" "aws_ebs_csi_driver":
│    7: resource "aws_eks_addon" "aws_ebs_csi_driver" {
│ 
╵
╷
│ Error: timed out waiting for the condition
│ 
│   with module.eks_blueprints_kubernetes_addons.module.aws_load_balancer_controller[0].module.helm_addon.helm_release.addon[0],
│   on .terraform/modules/eks_blueprints_kubernetes_addons/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {
│ 
╵
╷
│ Error: timed out waiting for the condition
│ 
│   with module.eks_blueprints_kubernetes_addons.module.cert_manager[0].module.helm_addon.helm_release.addon[0],
│   on .terraform/modules/eks_blueprints_kubernetes_addons/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {
│ 
╵
╷
│ Error: failed pre-install: timed out waiting for the condition
│ 
│   with module.eks_blueprints_kubernetes_addons.module.secrets_store_csi_driver[0].module.helm_addon.helm_release.addon[0],
│   on .terraform/modules/eks_blueprints_kubernetes_addons/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {
│ 
╵
╷
│ Error: timed out waiting for the condition
│ 
│   with module.eks_blueprints_kubernetes_addons.module.aws_fsx_csi_driver[0].module.helm_addon.helm_release.addon[0],
│   on .terraform/modules/eks_blueprints_kubernetes_addons/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {
│ 
╵
╷
│ Error: timed out waiting for the condition
│ 
│   with module.eks_blueprints_kubernetes_addons.module.aws_efs_csi_driver[0].module.helm_addon.helm_release.addon[0],
│   on .terraform/modules/eks_blueprints_kubernetes_addons/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {
│ 
╵
Makefile:27: recipe for target 'deploy-eks-blueprints-k8s-addons' failed
make: *** [deploy-eks-blueprints-k8s-addons] Error 1

**Comment by jsitu777** [comment] 2023-03-22 21:54
May I also know what region you are deploying cognito-rds-s3? It's a known issue that cognito doesn't work in some regions https://github.com/awslabs/kubeflow-manifests/issues/18

**Comment by renanmb** [comment] 2023-03-23 00:51
I am aware that Cognito is on us-east-1 by default, so I created the ceritficates so I could deploy on us-west-2

**Comment by surajkota** [comment] 2023-03-23 01:16
`make-deploy` command is actually running a set of [4 steps](https://github.com/awslabs/kubeflow-manifests/blob/main/deployments/cognito-rds-s3/terraform/Makefile#L3-L7)

```
init \
 create-vpc \
 create-eks-cluster \
 deploy-eks-blueprints-k8s-addons \
 deploy-kubeflow-components
```

From the errors you posted looks like are happening because the nodes are degraded after creation.

Addons are only installed as part of `deploy-eks-blueprints-k8s-addons` module after the cluster creation is successful which includes nodegroup creation. Terraform would not check for the health of nodes post creation. Did you check why are nodes became unavailable? Are you able to reproduce this? Also, have you changed the VPC or cluster settings or using the blueprints as-is?

**Comment by renanmb** [comment] 2023-03-23 01:42
I am using it as is no new vpc, yes I can reproduce, I added GPU managed node-group and set the min and desired to 0 as I wanted to scale-in to zero.
$ export CLUSTER_REGION="us-west-2"  or "us-east-1"
$ export CLUSTER_NAME="kubeflow-v1"

$ export TF_VAR_minio_aws_access_key_id=""
$ export TF_VAR_minio_aws_secret_access_key=""

$ export ROOT_DOMAIN="example.com"
$ export SUBDOMAIN="kubeflow.example.com"

$ export USER_POOL_NAME="kubeflow-users"

$ export USE_RDS="false"
$ export USE_S3="true"
$ export USE_COGNITO="true"
$ export LOAD_BALANCER_SCHEME="internet-facing"
$ export TF_VAR_create_subdomain="true"

$ export ENABLE_CULLING="true"
$ export CULL_IDLE_TIMEOUT="30"
$ export IDLENESS_CHECK_PERIOD="5"

$ export NODE_INSTANCE_TYPE_GPU="g5.2xlarge"

then loaded it all on the auto.tfvars

and below I only changed on the locals at the main.tf the min_size and desired_size
  managed_node_group_cpu = {
    node_group_name = "managed-ondemand-cpu"
    instance_types  = [var.node_instance_type]
    min_size        = 0
    desired_size    = 0
    max_size        = 10
    subnet_ids      = module.vpc.private_subnets
  }

  managed_node_group_gpu = local.using_gpu ? {
    node_group_name = "managed-ondemand-gpu"
    instance_types  = [var.node_instance_type_gpu]
    min_size        = 0
    desired_size    = 0
    max_size        = 5
    ami_type        = "AL2_x86_64_GPU"
    subnet_ids      = module.vpc.private_subnets
  } : null

**Comment by surajkota** [comment] 2023-03-23 19:39
Hi @renanmb, Cluster Autoscaler or Karpenter is not installed by default in these blueprints and hence the nodes would not scale automatically. This is feature is yet to be added. EKS blueprints does have an addon for it, feel free to enable it by adding - `enable_cluster_autoscaler = true` similar to [efs driver](https://github.com/awslabs/kubeflow-manifests/blob/main/deployments/cognito-rds-s3/terraform/main.tf#L148)

But for any of this to work you need some compute capacity and I would recommend setting the cpu nodegroup desired to be >=5 so that the pods can be scheduled, cluster autoscaler is also installed as a deployment. That might be the reason none of the controller pods are able to come up. This is expected and is not a race condition, your cluster might have got created according to the parameters you specified but it does not have capacity

Another thing, the `ROOT_DOMAIN` needs to be a [registered domain](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/domain-register.html) in your account for this to work and I recommend setting subdomain name to `platform.xyz`. Otherwise your full kubeflow domain would be `kubeflow.kubeflow.xyz`
```
$ export ROOT_DOMAIN="example.com"
$ export SUBDOMAIN="kubeflow.example.com"
```
Maybe you have masked it for purpose for this issue, ignore if that is not the case.

**Comment by renanmb** [comment] 2023-03-26 03:59
Ok, it did fix the problem. I cant believe it was a single line of code that I let pass !
Well, but I quite dont understand, there should be a way to Scale-in to zero to stop all instances when there is no activity.
That affects the GPU notebooks too. They dont Scale-in

**Comment by ananth102** [comment] 2023-04-06 19:03
Closing as issue has been resolved

**Closed by ananth102** 2023-04-06 19:03 UTC
Labels: bug
