### ISSUE TITLE
Error Deploying Kubeflow on EKS

### ISSUE THREAD

**Issue by HectorGonzalezBeltran** [awslabs/kubeflow-manifests#158] opened 2022-03-31 07:36 UTC
Hello everyone,

I've been following the guides for several days to install kubeflow on EKS with cognito, RDS and S3. The last test has been following this guide:

https://github.com/awslabs/kubeflow-manifests/tree/v1.3-branch/distributions/aws/examples/rds-s3

I have checked each step several times. I have used the python script indicated in the guide to generate and configure the resources. However, when I run the kustomize command, it fails with the following error:

```
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "[sidecar-injector.istio.io](http://sidecar-injector.istio.io/)": Post "[https://istiod.istio-system.svc:443/inject?timeout=30s](https://istiod.istio-system.svc/inject?timeout=30s)": no endpoints available for service "istiod"
[unable to recognize "STDIN": no matches for kind "Image" in version "[caching.internal.knative.dev/v1alpha1](http://caching.internal.knative.dev/v1alpha1)", unable to recognize "STDIN": no matches for kind "Certificate" in version "[cert-manager.io/v1alpha2](http://cert-manager.io/v1alpha2)", unable to recognize "STDIN": no matches for kind "ClusterIssuer" in version "[cert-manager.io/v1alpha2](http://cert-manager.io/v1alpha2)", unable to recognize "STDIN": no matches for kind "Issuer" in version "[cert-manager.io/v1alpha2](http://cert-manager.io/v1alpha2)", unable to recognize "STDIN": no matches for kind "Profile" in version "[kubeflow.org/v1beta1](http://kubeflow.org/v1beta1)", unable to recognize "STDIN": no matches for kind "CompositeController" in version "[metacontroller.k8s.io/v1alpha1](http://metacontroller.k8s.io/v1alpha1)", unable to recognize "STDIN": no matches for kind "DestinationRule" in version "[networking.istio.io/v1alpha3](http://networking.istio.io/v1alpha3)", unable to recognize "STDIN": no matches for kind "EnvoyFilter" in version "[networking.istio.io/v1alpha3](http://networking.istio.io/v1alpha3)", unable to recognize "STDIN": no matches for kind "Gateway" in version "[networking.istio.io/v1alpha3](http://networking.istio.io/v1alpha3)", unable to recognize "STDIN": no matches for kind "VirtualService" in version "[networking.istio.io/v1alpha3](http://networking.istio.io/v1alpha3)", unable to recognize "STDIN": no matches for kind "AuthorizationPolicy" in version "[security.istio.io/v1beta1](http://security.istio.io/v1beta1)"]
```

I have tried other guides and they all end up with some kind of error, any ideas will be of great help, thank you very much for your time.

Environment:
EKS yes
EKS Version: 1.9
Kubeflow version: 1.3.1
Kustomize version: kustomize/v3.2.3

The pods in the namespaces cert-manager and istio-system are running:

<img width="1193" alt="Screenshot 2022-03-31 at 09 04 18" src="https://user-images.githubusercontent.com/97881916/161002682-b8bebe64-b412-44d2-aaef-9230d7dba217.png">

<img width="1188" alt="Screenshot 2022-03-31 at 09 03 04" src="https://user-images.githubusercontent.com/97881916/161002711-97eaa670-4bd6-4317-af6e-f197f6ec4870.png">

Thanks,
Héctor.

**Comment by surajkota** [comment] 2022-03-31 18:01
Thank you Hector, I will try to reproduce it on my end. Few questions in the meantime:

- Were you using a new cluster for trying this out or an existing cluster? 
- Are able to reproduce it on a fresh cluster as well?
- From the logs, I think you are using the single line installation, is that correct? If you can try out the individual component installation, it will be helpful to know at which step do you start seeing this error. It will help minimize the scope for debugging

**Comment by HectorGonzalezBeltran** [comment] 2022-04-01 06:56
Hello Suraj! 

I have created a new cluster for the kubeflow installation. The cluster is created with the command shown in the guide:
 
https://github.com/awslabs/kubeflow-manifests/tree/v1.3-branch/distributions/aws/examples/rds-s3

In other tests I tried with the individual components and it failed with the following command
(Actually it didn't fail but the command stayed active but never finished):

`kustomize build common/cert-manager/cert-manager/base | kubectl apply -f -`

If you have any other questions, please let me know, thank you very much!

**Comment by Harikantipudi** [comment] 2022-04-01 13:33
Hello Hector,

I am not sure this can be the issue and i am sure it is not but can you try out with kustomize version 3.2.0 than 3.2.3 since 3.2.0 is a hard requirement and follow pre-requisites to the dot for version 1.3 . You are better off that way 

I will try reproducing the steps you followed too and come back

**Comment by HectorGonzalezBeltran** [comment] 2022-04-01 13:59
Hi! Thanks for your reply.
I keep getting error with kustomize version 3.2.0, you can see the following error:
<img width="1474" alt="Screenshot 2022-04-01 at 15 57 54" src="https://user-images.githubusercontent.com/97881916/161278312-46eee720-641f-4893-8cd8-b90110686cf5.png">
And the command just freezes there and never ends

**Comment by Harikantipudi** [comment] 2022-04-01 14:41
https://github.com/kubeflow/manifests/issues/2086

Can you try this out, solution is out there !!. Let me know

**Comment by surajkota** [comment] 2022-04-04 20:32
Thanks @Harikantipudi

Here are some more of the relevant existing closed threads I found related to this issue:

https://github.com/kubeflow/manifests/issues/2096#issuecomment-1002851249
https://github.com/kubeflow/manifests/issues/2086#issuecomment-995868483
https://github.com/kubeflow/manifests/issues/2062

There are a few more as well. On a preliminary analysis it looks like some of the nodes with `NoSchedule` label because of which some pods fail to get scheduled or an issue with clean uninstallation of kubeflow.

Since you mentioned you tried multiple guides, I am wondering if your issue is related to the `validatingwebhookconfigurations` not deleted properly

can you try running:

```
kubectl delete mutatingwebhookconfigurations.admissionregistration.k8s.io webhook.eventing.knative.dev webhook.istio.networking.internal.knative.dev webhook.serving.knative.dev

kubectl delete validatingwebhookconfigurations.admissionregistration.k8s.io config.webhook.eventing.knative.dev config.webhook.istio.networking.internal.knative.dev config.webhook.serving.knative.dev

kubectl delete endpoints -n default mxnet-operator pytorch-operator tf-operator
```

**Comment by HectorGonzalezBeltran** [comment] 2022-04-07 07:02
Hello! thank you all for your answers, I will try those solutions. Sorry for not replying earlier, it has not been possible for me. I will try these solutions and let you know.

**Comment by ryansteakley** [comment] 2022-04-22 18:27
This ticket will be resolved in the next two weeks if you don't have any further comments.

**Closed** 2022-06-08 00:21 UTC
Labels: bug
